export enum CALL_STATE {
  READY = 'ready',
  LOBBY = 'lobby',
  JOINING = 'joining',
  JOINED = 'joined',
  ENDED = 'ended',
  ERROR = 'error',
  FULL = 'full',
  EXPIRED = 'expired',
  NOT_BEFORE = 'nbf',
  REMOVED = 'removed-from-call',
  REDIRECTING = 'redirecting',
  NOT_FOUND = 'not-found',
  NOT_ALLOWED = 'not-allowed',
  AWAITING_ARGS = 'awaiting-args',
  NOT_SECURE = 'not-secure',
}
