# # https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
#
# version: 2
# updates:
#   - package-ecosystem: 'npm'
#     directory: '/'
#     schedule:
#       interval: 'daily'
#     commit-message:
#       prefix: 'deps prod'
#       prefix-development: 'deps dev'
#       include: 'scope'
#     labels:
#       - 'npm'
#       - 'dependencies'
#
#   - package-ecosystem: 'github-actions'
#     directory: '/'
#     schedule:
#       interval: 'daily'
