version: '3.8'

services:
  mongo:
    image: bitnami/mongodb:latest
    restart: always
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    networks:
      - fm-main-api

  redis:
    image: bitnami/redis:latest
    restart: always
    container_name: 'redis'
    environment:
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
    ports:
      - '6379:6379'
    volumes:
      - redis:/data/db
    networks:
      - fm-main-api

  api:
    image: api
    restart: always
    container_name: 'main-api'
    environment:
      - NODE_ENV=production
    ports:
      - ${API_PORT}:3333
    depends_on:
      - mongo
    networks:
      - fm-main-api

networks:
  fm-main-api:

volumes:
  mongodb:
  redis:
