version: '3.8'

services:
  mongo:
    image: mongo:${MONGO_VERSION}
    restart: always
    container_name: 'mongo'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}
    volumes:
      - mongodb:/data/db
    networks:
      - fm-main-api

  api:
    image: api
    restart: always
    container_name: 'main-api'
    environment:
      - NODE_ENV=production
      - DATABASE_URI=mongodb://mongo:27017/${MONGO_COLLECTION_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - ${API_PORT}:3333
    depends_on:
      - mongo
    networks:
      - fm-main-api

networks:
  fm-main-api:

volumes:
  mongodb:
