export enum ParticipantsActionType {
  JOINED_MEETING = 'JOINED_MEETING',
  ACTIVE_SPEAKER = 'ACTIVE_SPEAKER',
  PARTICIPANT_JOINED = 'PARTICIPANT_JOINED',
  PARTICIPANT_UPDATED = 'PARTICIPANT_UPDATED',
  PARTICIPANT_LEFT = 'PARTICIPANT_LEFT',
}
