query GetCategoriesPaginate($parentId: ID!, $page: Int!, $limit: Int!) {
  categoriesPaginate(
    input: { parentId: $parentId, page: $page, limit: $limit }
  ) {
    categories {
      id
      title
    }
    pagesCount
  }
}
