query GetMaterialsPaginate($categoryId: ID!, $page: Int!, $limit: Int!) {
  materialsPaginate(
    dto: { categoryId: $categoryId, page: $page, limit: $limit }
  ) {
    materials {
      id
      title
    }
    pagesCount
  }
}
