name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build w/ Nx Cloud
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.3
    with:
      parallel-commands: |
        yarn nx-cloud record -- yarn nx workspace-lint
        yarn nx-cloud record -- yarn nx format:check
      parallel-commands-on-agents: |
        yarn nx affected --target=lint --parallel=3
        yarn nx affected --target=test --parallel=3 --ci --code-coverage
        yarn nx affected --target=build --parallel=3 --configuration=production

  agents:
    name: Nx Cloud Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.3
    with:
      number-of-agents: 3

  dockerize:
    name: Docker build
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: yarn nx affected --target=docker

  compose:
    name: Docker Compose
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose up -d
